name: endpoints-cd-staging

permissions:
  id-token: write # required to use OIDC authentication
  contents: read # required to check out the code from the repo
  issues: write

concurrency: endpoints-cd-staging

on:
  workflow_dispatch:

jobs:
  manual:
    uses: emrullahshn/github_actions_test/.github/workflows/cd.yml@main

    secrets: inherit
